/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AttributesField: typeof import('./src/components/AttributesField.vue')['default']
    EntityCollections: typeof import('./src/components/EntityCollections.vue')['default']
    EntityField: typeof import('./src/components/EntityField.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    U2wareAvatar: typeof import('./src/components/U2wareAvatar.vue')['default']
    U2wareFooter: typeof import('./src/components/U2wareFooter.vue')['default']
  }
}
