/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/accounts': RouteRecordInfo<'/accounts', '/accounts', Record<never, never>, Record<never, never>, '/accounts/login' | '/accounts/logoff' | '/accounts/logon' | '/accounts/logout'>,
    '/accounts/login': RouteRecordInfo<'/accounts/login', '/accounts/login', Record<never, never>, Record<never, never>>,
    '/accounts/logoff': RouteRecordInfo<'/accounts/logoff', '/accounts/logoff', Record<never, never>, Record<never, never>>,
    '/accounts/logon': RouteRecordInfo<'/accounts/logon', '/accounts/logon', Record<never, never>, Record<never, never>>,
    '/accounts/logout': RouteRecordInfo<'/accounts/logout', '/accounts/logout', Record<never, never>, Record<never, never>>,
    '/contents': RouteRecordInfo<'/contents', '/contents', Record<never, never>, Record<never, never>, '/contents/' | '/contents/accounts' | '/contents/busDrivers' | '/contents/busRoutes' | '/contents/busStops' | '/contents/buses' | '/contents/repairs' | '/contents/sessions' | '/contents/userAccount'>,
    '/contents/': RouteRecordInfo<'/contents/', '/contents', Record<never, never>, Record<never, never>>,
    '/contents/accounts': RouteRecordInfo<'/contents/accounts', '/contents/accounts', Record<never, never>, Record<never, never>>,
    '/contents/busDrivers': RouteRecordInfo<'/contents/busDrivers', '/contents/busDrivers', Record<never, never>, Record<never, never>>,
    '/contents/buses': RouteRecordInfo<'/contents/buses', '/contents/buses', Record<never, never>, Record<never, never>>,
    '/contents/busRoutes': RouteRecordInfo<'/contents/busRoutes', '/contents/busRoutes', Record<never, never>, Record<never, never>>,
    '/contents/busStops': RouteRecordInfo<'/contents/busStops', '/contents/busStops', Record<never, never>, Record<never, never>>,
    '/contents/repairs': RouteRecordInfo<'/contents/repairs', '/contents/repairs', Record<never, never>, Record<never, never>>,
    '/contents/sessions': RouteRecordInfo<'/contents/sessions', '/contents/sessions', Record<never, never>, Record<never, never>>,
    '/contents/userAccount': RouteRecordInfo<'/contents/userAccount', '/contents/userAccount', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/apps/02_bus/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/apps/02_bus/pages/[...path].vue': {
      routes: '/[...path]'
      views: never
    }
    'src/apps/02_bus/pages/accounts.vue': {
      routes: '/accounts' | '/accounts/login' | '/accounts/logoff' | '/accounts/logon' | '/accounts/logout'
      views: 'default'
    }
    'src/apps/02_bus/pages/accounts/login.vue': {
      routes: '/accounts/login'
      views: never
    }
    'src/apps/02_bus/pages/accounts/logoff.vue': {
      routes: '/accounts/logoff'
      views: never
    }
    'src/apps/02_bus/pages/accounts/logon.vue': {
      routes: '/accounts/logon'
      views: never
    }
    'src/apps/02_bus/pages/accounts/logout.vue': {
      routes: '/accounts/logout'
      views: never
    }
    'src/apps/02_bus/pages/contents.vue': {
      routes: '/contents' | '/contents/' | '/contents/accounts' | '/contents/busDrivers' | '/contents/buses' | '/contents/busRoutes' | '/contents/busStops' | '/contents/repairs' | '/contents/sessions' | '/contents/userAccount'
      views: 'default'
    }
    'src/apps/02_bus/pages/contents/index.vue': {
      routes: '/contents/'
      views: never
    }
    'src/apps/02_bus/pages/contents/accounts.vue': {
      routes: '/contents/accounts'
      views: never
    }
    'src/apps/02_bus/pages/contents/busDrivers.vue': {
      routes: '/contents/busDrivers'
      views: never
    }
    'src/apps/02_bus/pages/contents/buses.vue': {
      routes: '/contents/buses'
      views: never
    }
    'src/apps/02_bus/pages/contents/busRoutes.vue': {
      routes: '/contents/busRoutes'
      views: never
    }
    'src/apps/02_bus/pages/contents/busStops.vue': {
      routes: '/contents/busStops'
      views: never
    }
    'src/apps/02_bus/pages/contents/repairs.vue': {
      routes: '/contents/repairs'
      views: never
    }
    'src/apps/02_bus/pages/contents/sessions.vue': {
      routes: '/contents/sessions'
      views: never
    }
    'src/apps/02_bus/pages/contents/userAccount.vue': {
      routes: '/contents/userAccount'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
